on:
  push:
concurrency: build
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.x'
    - name: Run go build
      run: CGO_ENABLED=0 go build -o docker/lumina-proxy/ ./cmd/lumina-proxy
    - name: Build docker container and push
      if: github.ref == 'refs/heads/master'
      env:
        REGISTRY_USERNAME: youfu
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        IMAGE_PATH: registry-1.docker.io/youfu/lumina-proxy:latest
      run: |
        docker build --tag "${IMAGE_PATH}" docker/lumina-proxy/
        docker login --username "${REGISTRY_USERNAME}" --password "${REGISTRY_PASSWORD}" "${IMAGE_PATH%%/*}"
        docker push "${IMAGE_PATH}"
